import type { VocabWord } from "@/types";

export const WORDS: VocabWord[] = [
  // ─── NIVEAU 1 — 50 mots ultra-fréquents ───────────────────────────────────
  { id: "1-001", word: "cat",    translation: "chat",     level: 1, category: "animaux",      emoji: "🐱", phonetic: "kæt"     },
  { id: "1-002", word: "dog",    translation: "chien",    level: 1, category: "animaux",      emoji: "🐶", phonetic: "dɒɡ"     },
  { id: "1-003", word: "fish",   translation: "poisson",  level: 1, category: "animaux",      emoji: "🐟", phonetic: "fɪʃ"     },
  { id: "1-004", word: "bird",   translation: "oiseau",   level: 1, category: "animaux",      emoji: "🐦", phonetic: "bɜːrd"   },
  { id: "1-005", word: "run",    translation: "courir",   level: 1, category: "actions",      emoji: "🏃", phonetic: "rʌn"     },
  { id: "1-006", word: "jump",   translation: "sauter",   level: 1, category: "actions",      emoji: "🦘", phonetic: "dʒʌmp"   },
  { id: "1-007", word: "eat",    translation: "manger",   level: 1, category: "actions",      emoji: "🍽️", phonetic: "iːt"     },
  { id: "1-008", word: "drink",  translation: "boire",    level: 1, category: "actions",      emoji: "🥤", phonetic: "drɪŋk"   },
  { id: "1-009", word: "sleep",  translation: "dormir",   level: 1, category: "actions",      emoji: "😴", phonetic: "sliːp"   },
  { id: "1-010", word: "play",   translation: "jouer",    level: 1, category: "actions",      emoji: "🎮", phonetic: "pleɪ"    },
  { id: "1-011", word: "walk",   translation: "marcher",  level: 1, category: "actions",      emoji: "🚶", phonetic: "wɔːk"    },
  { id: "1-012", word: "sing",   translation: "chanter",  level: 1, category: "actions",      emoji: "🎵", phonetic: "sɪŋ"     },
  { id: "1-013", word: "read",   translation: "lire",     level: 1, category: "actions",      emoji: "📖", phonetic: "riːd"    },
  { id: "1-014", word: "happy",  translation: "heureux",  level: 1, category: "émotions",     emoji: "😊", phonetic: "ˈhæpi"   },
  { id: "1-015", word: "sad",    translation: "triste",   level: 1, category: "émotions",     emoji: "😢", phonetic: "sæd"     },
  { id: "1-016", word: "big",    translation: "grand",    level: 1, category: "descriptions", emoji: "🐘", phonetic: "bɪɡ"     },
  { id: "1-017", word: "small",  translation: "petit",    level: 1, category: "descriptions", emoji: "🐭", phonetic: "smɔːl"   },
  { id: "1-018", word: "hot",    translation: "chaud",    level: 1, category: "descriptions", emoji: "🌡️", phonetic: "hɒt"     },
  { id: "1-019", word: "cold",   translation: "froid",    level: 1, category: "descriptions", emoji: "🧊", phonetic: "koʊld"   },
  { id: "1-020", word: "good",   translation: "bien",     level: 1, category: "descriptions", emoji: "👍", phonetic: "ɡʊd"     },
  { id: "1-021", word: "red",    translation: "rouge",    level: 1, category: "couleurs",     emoji: "🔴", phonetic: "rɛd"     },
  { id: "1-022", word: "blue",   translation: "bleu",     level: 1, category: "couleurs",     emoji: "🔵", phonetic: "bluː"    },
  { id: "1-023", word: "green",  translation: "vert",     level: 1, category: "couleurs",     emoji: "💚", phonetic: "ɡriːn"   },
  { id: "1-024", word: "yellow", translation: "jaune",    level: 1, category: "couleurs",     emoji: "💛", phonetic: "ˈjɛloʊ"  },
  { id: "1-025", word: "book",   translation: "livre",    level: 1, category: "objets",       emoji: "📚", phonetic: "bʊk"     },
  { id: "1-026", word: "ball",   translation: "balle",    level: 1, category: "objets",       emoji: "⚽", phonetic: "bɔːl"    },
  { id: "1-027", word: "car",    translation: "voiture",  level: 1, category: "objets",       emoji: "🚗", phonetic: "kɑːr"    },
  { id: "1-028", word: "door",   translation: "porte",    level: 1, category: "objets",       emoji: "🚪", phonetic: "dɔːr"    },
  { id: "1-029", word: "house",  translation: "maison",   level: 1, category: "lieux",        emoji: "🏠", phonetic: "haʊs"    },
  { id: "1-030", word: "school", translation: "école",    level: 1, category: "lieux",        emoji: "🏫", phonetic: "skuːl"   },
  { id: "1-031", word: "tree",   translation: "arbre",    level: 1, category: "nature",       emoji: "🌳", phonetic: "triː"    },
  { id: "1-032", word: "water",  translation: "eau",      level: 1, category: "nature",       emoji: "💧", phonetic: "ˈwɔːtər" },
  { id: "1-033", word: "sun",    translation: "soleil",   level: 1, category: "nature",       emoji: "☀️", phonetic: "sʌn"     },
  { id: "1-034", word: "moon",   translation: "lune",     level: 1, category: "nature",       emoji: "🌙", phonetic: "muːn"    },
  { id: "1-035", word: "star",   translation: "étoile",   level: 1, category: "nature",       emoji: "⭐", phonetic: "stɑːr"   },
  { id: "1-036", word: "flower", translation: "fleur",    level: 1, category: "nature",       emoji: "🌸", phonetic: "ˈflaʊər" },
  { id: "1-037", word: "apple",  translation: "pomme",    level: 1, category: "nourriture",   emoji: "🍎", phonetic: "ˈæpəl"   },
  { id: "1-038", word: "cake",   translation: "gâteau",   level: 1, category: "nourriture",   emoji: "🎂", phonetic: "keɪk"    },
  { id: "1-039", word: "milk",   translation: "lait",     level: 1, category: "nourriture",   emoji: "🥛", phonetic: "mɪlk"    },
  { id: "1-040", word: "egg",    translation: "œuf",      level: 1, category: "nourriture",   emoji: "🥚", phonetic: "ɛɡ"      },
  { id: "1-041", word: "boy",    translation: "garçon",   level: 1, category: "personnes",    emoji: "👦", phonetic: "bɔɪ"     },
  { id: "1-042", word: "girl",   translation: "fille",    level: 1, category: "personnes",    emoji: "👧", phonetic: "ɡɜːrl"   },
  { id: "1-043", word: "baby",   translation: "bébé",     level: 1, category: "personnes",    emoji: "👶", phonetic: "ˈbeɪbi"  },
  { id: "1-044", word: "friend", translation: "ami",      level: 1, category: "personnes",    emoji: "🤝", phonetic: "frɛnd"   },
  { id: "1-045", word: "love",   translation: "amour",    level: 1, category: "émotions",     emoji: "❤️", phonetic: "lʌv"     },
  { id: "1-046", word: "hand",   translation: "main",     level: 1, category: "corps",        emoji: "✋", phonetic: "hænd"    },
  { id: "1-047", word: "eye",    translation: "œil",      level: 1, category: "corps",        emoji: "👁️", phonetic: "aɪ"      },
  { id: "1-048", word: "day",    translation: "jour",     level: 1, category: "temps",        emoji: "🌅", phonetic: "deɪ"     },
  { id: "1-049", word: "night",  translation: "nuit",     level: 1, category: "temps",        emoji: "🌃", phonetic: "naɪt"    },
  { id: "1-050", word: "open",   translation: "ouvrir",   level: 1, category: "actions",      emoji: "🔓", phonetic: "ˈoʊpən"  },

  // ─── NIVEAU 2 — 50 mots fréquents ────────────────────────────────────────
  { id: "2-001", word: "beautiful",  translation: "beau/belle",       level: 2, category: "descriptions", emoji: "🌺", phonetic: "ˈbjuːtɪfəl"  },
  { id: "2-002", word: "angry",      translation: "en colère",        level: 2, category: "émotions",     emoji: "😠", phonetic: "ˈæŋɡri"      },
  { id: "2-003", word: "hungry",     translation: "affamé",           level: 2, category: "émotions",     emoji: "🍽️", phonetic: "ˈhʌŋɡri"     },
  { id: "2-004", word: "tired",      translation: "fatigué",          level: 2, category: "émotions",     emoji: "😪", phonetic: "ˈtaɪərd"     },
  { id: "2-005", word: "excited",    translation: "enthousiaste",     level: 2, category: "émotions",     emoji: "🤩", phonetic: "ɪkˈsaɪtɪd"  },
  { id: "2-006", word: "family",     translation: "famille",          level: 2, category: "personnes",    emoji: "👨‍👩‍👧", phonetic: "ˈfæməli"  },
  { id: "2-007", word: "garden",     translation: "jardin",           level: 2, category: "lieux",        emoji: "🌻", phonetic: "ˈɡɑːrdən"    },
  { id: "2-008", word: "animal",     translation: "animal",           level: 2, category: "nature",       emoji: "🦁", phonetic: "ˈænɪməl"     },
  { id: "2-009", word: "weather",    translation: "météo",            level: 2, category: "nature",       emoji: "🌤️", phonetic: "ˈwɛðər"      },
  { id: "2-010", word: "always",     translation: "toujours",         level: 2, category: "descriptions", emoji: "🔁", phonetic: "ˈɔːlweɪz"    },
  { id: "2-011", word: "never",      translation: "jamais",           level: 2, category: "descriptions", emoji: "🚫", phonetic: "ˈnɛvər"      },
  { id: "2-012", word: "together",   translation: "ensemble",         level: 2, category: "social",       emoji: "🤗", phonetic: "təˈɡɛðər"    },
  { id: "2-013", word: "important",  translation: "important",        level: 2, category: "descriptions", emoji: "⚠️", phonetic: "ɪmˈpɔːrtənt" },
  { id: "2-014", word: "careful",    translation: "prudent",          level: 2, category: "descriptions", emoji: "🛡️", phonetic: "ˈkɛːrfəl"    },
  { id: "2-015", word: "outside",    translation: "dehors",           level: 2, category: "lieux",        emoji: "🌿", phonetic: "ˈaʊtsaɪd"    },
  { id: "2-016", word: "laugh",      translation: "rire",             level: 2, category: "actions",      emoji: "😂", phonetic: "læf"          },
  { id: "2-017", word: "listen",     translation: "écouter",          level: 2, category: "actions",      emoji: "👂", phonetic: "ˈlɪsən"      },
  { id: "2-018", word: "share",      translation: "partager",         level: 2, category: "actions",      emoji: "🤲", phonetic: "ʃɛr"          },
  { id: "2-019", word: "remember",   translation: "se souvenir",      level: 2, category: "actions",      emoji: "🧠", phonetic: "rɪˈmɛmbər"   },
  { id: "2-020", word: "different",  translation: "différent",        level: 2, category: "descriptions", emoji: "🔀", phonetic: "ˈdɪfərənt"   },
  { id: "2-021", word: "story",      translation: "histoire",         level: 2, category: "objets",       emoji: "📖", phonetic: "ˈstɔːri"     },
  { id: "2-022", word: "window",     translation: "fenêtre",          level: 2, category: "objets",       emoji: "🪟", phonetic: "ˈwɪndoʊ"    },
  { id: "2-023", word: "morning",    translation: "matin",            level: 2, category: "temps",        emoji: "🌄", phonetic: "ˈmɔːrnɪŋ"   },
  { id: "2-024", word: "evening",    translation: "soir",             level: 2, category: "temps",        emoji: "🌆", phonetic: "ˈiːvnɪŋ"    },
  { id: "2-025", word: "summer",     translation: "été",              level: 2, category: "temps",        emoji: "☀️", phonetic: "ˈsʌmər"     },
  { id: "2-026", word: "winter",     translation: "hiver",            level: 2, category: "temps",        emoji: "❄️", phonetic: "ˈwɪntər"    },
  { id: "2-027", word: "music",      translation: "musique",          level: 2, category: "arts",         emoji: "🎵", phonetic: "ˈmjuːzɪk"   },
  { id: "2-028", word: "dance",      translation: "danser",           level: 2, category: "arts",         emoji: "💃", phonetic: "dæns"        },
  { id: "2-029", word: "paint",      translation: "peindre",          level: 2, category: "arts",         emoji: "🎨", phonetic: "peɪnt"       },
  { id: "2-030", word: "count",      translation: "compter",          level: 2, category: "actions",      emoji: "🔢", phonetic: "kaʊnt"       },
  { id: "2-031", word: "clean",      translation: "nettoyer",         level: 2, category: "actions",      emoji: "🧹", phonetic: "kliːn"       },
  { id: "2-032", word: "build",      translation: "construire",       level: 2, category: "actions",      emoji: "🏗️", phonetic: "bɪld"        },
  { id: "2-033", word: "think",      translation: "penser",           level: 2, category: "actions",      emoji: "💭", phonetic: "θɪŋk"        },
  { id: "2-034", word: "help",       translation: "aider",            level: 2, category: "actions",      emoji: "🤝", phonetic: "hɛlp"        },
  { id: "2-035", word: "forest",     translation: "forêt",            level: 2, category: "nature",       emoji: "🌲", phonetic: "ˈfɒrɪst"    },
  { id: "2-036", word: "ocean",      translation: "océan",            level: 2, category: "nature",       emoji: "🌊", phonetic: "ˈoʊʃən"     },
  { id: "2-037", word: "mountain",   translation: "montagne",         level: 2, category: "nature",       emoji: "⛰️", phonetic: "ˈmaʊntən"   },
  { id: "2-038", word: "planet",     translation: "planète",          level: 2, category: "nature",       emoji: "🪐", phonetic: "ˈplænɪt"    },
  { id: "2-039", word: "kitchen",    translation: "cuisine",          level: 2, category: "lieux",        emoji: "🍳", phonetic: "ˈkɪtʃɪn"    },
  { id: "2-040", word: "bedroom",    translation: "chambre",          level: 2, category: "lieux",        emoji: "🛏️", phonetic: "ˈbɛdruːm"   },
  { id: "2-041", word: "purple",     translation: "violet",           level: 2, category: "couleurs",     emoji: "💜", phonetic: "ˈpɜːrpəl"   },
  { id: "2-042", word: "orange",     translation: "orange",           level: 2, category: "couleurs",     emoji: "🟠", phonetic: "ˈɒrɪndʒ"    },
  { id: "2-043", word: "birthday",   translation: "anniversaire",     level: 2, category: "social",       emoji: "🎂", phonetic: "ˈbɜːrθdeɪ"  },
  { id: "2-044", word: "present",    translation: "cadeau",           level: 2, category: "objets",       emoji: "🎁", phonetic: "ˈprɛzənt"   },
  { id: "2-045", word: "learn",      translation: "apprendre",        level: 2, category: "actions",      emoji: "📚", phonetic: "lɜːrn"       },
  { id: "2-046", word: "teach",      translation: "enseigner",        level: 2, category: "actions",      emoji: "👩‍🏫", phonetic: "tiːtʃ"   },
  { id: "2-047", word: "write",      translation: "écrire",           level: 2, category: "actions",      emoji: "✏️", phonetic: "raɪt"        },
  { id: "2-048", word: "draw",       translation: "dessiner",         level: 2, category: "arts",         emoji: "🖍️", phonetic: "drɔː"        },
  { id: "2-049", word: "throw",      translation: "lancer",           level: 2, category: "actions",      emoji: "🎯", phonetic: "θroʊ"        },
  { id: "2-050", word: "carry",      translation: "porter",           level: 2, category: "actions",      emoji: "🧳", phonetic: "ˈkæri"       },

  // ─── NIVEAU 3 — 50 mots enrichis ─────────────────────────────────────────
  { id: "3-001", word: "adventure",   translation: "aventure",          level: 3, category: "thèmes",       emoji: "🗺️", phonetic: "ədˈvɛntʃər"    },
  { id: "3-002", word: "discover",    translation: "découvrir",         level: 3, category: "actions",      emoji: "🔍", phonetic: "dɪˈskʌvər"     },
  { id: "3-003", word: "imagine",     translation: "imaginer",          level: 3, category: "actions",      emoji: "💭", phonetic: "ɪˈmædʒɪn"      },
  { id: "3-004", word: "whisper",     translation: "chuchoter",         level: 3, category: "actions",      emoji: "🤫", phonetic: "ˈwɪspər"        },
  { id: "3-005", word: "curious",     translation: "curieux",           level: 3, category: "descriptions", emoji: "🧐", phonetic: "ˈkjʊriəs"      },
  { id: "3-006", word: "gentle",      translation: "doux/douce",        level: 3, category: "descriptions", emoji: "🕊️", phonetic: "ˈdʒɛntl"        },
  { id: "3-007", word: "enormous",    translation: "énorme",            level: 3, category: "descriptions", emoji: "🐋", phonetic: "ɪˈnɔːrməs"     },
  { id: "3-008", word: "delicious",   translation: "délicieux",         level: 3, category: "descriptions", emoji: "😋", phonetic: "dɪˈlɪʃəs"       },
  { id: "3-009", word: "mysterious",  translation: "mystérieux",        level: 3, category: "descriptions", emoji: "🔮", phonetic: "mɪˈstɪəriəs"    },
  { id: "3-010", word: "journey",     translation: "voyage",            level: 3, category: "thèmes",       emoji: "🚂", phonetic: "ˈdʒɜːrni"       },
  { id: "3-011", word: "protect",     translation: "protéger",          level: 3, category: "actions",      emoji: "🛡️", phonetic: "prəˈtɛkt"       },
  { id: "3-012", word: "celebrate",   translation: "célébrer",          level: 3, category: "actions",      emoji: "🎉", phonetic: "ˈsɛlɪbreɪt"    },
  { id: "3-013", word: "silence",     translation: "silence",           level: 3, category: "concepts",     emoji: "🤫", phonetic: "ˈsaɪləns"       },
  { id: "3-014", word: "kindness",    translation: "gentillesse",       level: 3, category: "concepts",     emoji: "💛", phonetic: "ˈkaɪndnəs"      },
  { id: "3-015", word: "courage",     translation: "courage",           level: 3, category: "concepts",     emoji: "🦁", phonetic: "ˈkɜːrɪdʒ"       },
  { id: "3-016", word: "wonderful",   translation: "merveilleux",       level: 3, category: "descriptions", emoji: "✨", phonetic: "ˈwʌndərfəl"     },
  { id: "3-017", word: "fantastic",   translation: "fantastique",       level: 3, category: "descriptions", emoji: "🌟", phonetic: "fænˈtæstɪk"     },
  { id: "3-018", word: "impossible",  translation: "impossible",        level: 3, category: "descriptions", emoji: "🚀", phonetic: "ɪmˈpɒsɪbəl"    },
  { id: "3-019", word: "rainbow",     translation: "arc-en-ciel",       level: 3, category: "nature",       emoji: "🌈", phonetic: "ˈreɪnboʊ"       },
  { id: "3-020", word: "butterfly",   translation: "papillon",          level: 3, category: "animaux",      emoji: "🦋", phonetic: "ˈbʌtərflaɪ"    },
  { id: "3-021", word: "universe",    translation: "univers",           level: 3, category: "concepts",     emoji: "🌌", phonetic: "ˈjuːnɪvɜːrs"   },
  { id: "3-022", word: "treasure",    translation: "trésor",            level: 3, category: "objets",       emoji: "💎", phonetic: "ˈtrɛʒər"        },
  { id: "3-023", word: "magical",     translation: "magique",           level: 3, category: "descriptions", emoji: "✨", phonetic: "ˈmædʒɪkəl"     },
  { id: "3-024", word: "friendship",  translation: "amitié",            level: 3, category: "concepts",     emoji: "👫", phonetic: "ˈfrɛndʃɪp"      },
  { id: "3-025", word: "beginning",   translation: "début",             level: 3, category: "concepts",     emoji: "🌱", phonetic: "bɪˈɡɪnɪŋ"      },
  { id: "3-026", word: "respect",     translation: "respect",           level: 3, category: "concepts",     emoji: "🙏", phonetic: "rɪˈspɛkt"       },
  { id: "3-027", word: "grateful",    translation: "reconnaissant",     level: 3, category: "émotions",     emoji: "🙏", phonetic: "ˈɡreɪtfəl"     },
  { id: "3-028", word: "champion",    translation: "champion",          level: 3, category: "thèmes",       emoji: "🏆", phonetic: "ˈtʃæmpiən"     },
  { id: "3-029", word: "creativity",  translation: "créativité",        level: 3, category: "concepts",     emoji: "🎨", phonetic: "kriˌeɪˈtɪvɪti"  },
  { id: "3-030", word: "inspire",     translation: "inspirer",          level: 3, category: "actions",      emoji: "💫", phonetic: "ɪnˈspaɪər"     },
  { id: "3-031", word: "brilliant",   translation: "brillant",          level: 3, category: "descriptions", emoji: "💡", phonetic: "ˈbrɪljənt"      },
  { id: "3-032", word: "explore",     translation: "explorer",          level: 3, category: "actions",      emoji: "🧭", phonetic: "ɪkˈsplɔːr"     },
  { id: "3-033", word: "freedom",     translation: "liberté",           level: 3, category: "concepts",     emoji: "🕊️", phonetic: "ˈfriːdəm"       },
  { id: "3-034", word: "harmony",     translation: "harmonie",          level: 3, category: "concepts",     emoji: "🎶", phonetic: "ˈhɑːrməni"     },
  { id: "3-035", word: "patience",    translation: "patience",          level: 3, category: "concepts",     emoji: "⏳", phonetic: "ˈpeɪʃəns"      },
  { id: "3-036", word: "surprise",    translation: "surprise",          level: 3, category: "émotions",     emoji: "🎁", phonetic: "sərˈpraɪz"     },
  { id: "3-037", word: "powerful",    translation: "puissant",          level: 3, category: "descriptions", emoji: "💪", phonetic: "ˈpaʊərfəl"     },
  { id: "3-038", word: "incredible",  translation: "incroyable",        level: 3, category: "descriptions", emoji: "🤯", phonetic: "ɪnˈkrɛdɪbəl"   },
  { id: "3-039", word: "challenge",   translation: "défi",              level: 3, category: "concepts",     emoji: "🏅", phonetic: "ˈtʃælɪndʒ"     },
  { id: "3-040", word: "achieve",     translation: "accomplir",         level: 3, category: "actions",      emoji: "🎯", phonetic: "əˈtʃiːv"        },
  { id: "3-041", word: "transform",   translation: "transformer",       level: 3, category: "actions",      emoji: "🔄", phonetic: "trænsˈfɔːrm"    },
  { id: "3-042", word: "dream",       translation: "rêver",             level: 3, category: "actions",      emoji: "🌙", phonetic: "driːm"           },
  { id: "3-043", word: "believe",     translation: "croire",            level: 3, category: "actions",      emoji: "⭐", phonetic: "bɪˈliːv"        },
  { id: "3-044", word: "positive",    translation: "positif",           level: 3, category: "descriptions", emoji: "😁", phonetic: "ˈpɒzɪtɪv"      },
  { id: "3-045", word: "confident",   translation: "confiant",          level: 3, category: "descriptions", emoji: "💪", phonetic: "ˈkɒnfɪdənt"    },
  { id: "3-046", word: "generous",    translation: "généreux",          level: 3, category: "descriptions", emoji: "🎁", phonetic: "ˈdʒɛnərəs"     },
  { id: "3-047", word: "wise",        translation: "sage",              level: 3, category: "descriptions", emoji: "🦉", phonetic: "waɪz"            },
  { id: "3-048", word: "ancient",     translation: "ancien",            level: 3, category: "descriptions", emoji: "🏛️", phonetic: "ˈeɪnʃənt"      },
  { id: "3-049", word: "volcano",     translation: "volcan",            level: 3, category: "nature",       emoji: "🌋", phonetic: "vɒlˈkeɪnoʊ"    },
  { id: "3-050", word: "telescope",   translation: "télescope",         level: 3, category: "objets",       emoji: "🔭", phonetic: "ˈtɛlɪskoʊp"    },
];

export function getWordsByLevel(level: 1 | 2 | 3 | "all"): VocabWord[] {
  if (level === "all") return WORDS;
  return WORDS.filter((w) => w.level === level);
}

export function getWordById(id: string): VocabWord | undefined {
  return WORDS.find((w) => w.id === id);
}

export function getRandomWords(count: number, exclude?: string[]): VocabWord[] {
  const pool = exclude ? WORDS.filter((w) => !exclude.includes(w.id)) : WORDS;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getDistractors(word: VocabWord, count = 3): VocabWord[] {
  const sameLevel = WORDS.filter((w) => w.level === word.level && w.id !== word.id);
  const sameCategory = sameLevel.filter((w) => w.category === word.category);
  const pool = sameCategory.length >= count ? sameCategory : sameLevel;
  return [...pool].sort(() => Math.random() - 0.5).slice(0, count);
}
